#!/usr/bin/env php
<?php

if (isset($argv[1]) && $argv[1] == "next") {
    $week = "next";
}else {
    $week = "this";
}

$weekNumber = (int)date("W", strtotime( 'monday ' . $week . ' week' ) );
$monday = date( 'l\, F j Y', strtotime( 'monday ' . $week . ' week' ) );
$tuesday = date( 'l\, F j Y', strtotime( 'tuesday ' . $week . ' week' ) );
$wednesday = date( 'l\, F j Y', strtotime( 'wednesday ' . $week . ' week' ) );
$thursday = date( 'l\, F j Y', strtotime( 'thursday ' . $week . ' week' ) );
$friday = date( 'l\, F j Y', strtotime( 'friday ' . $week . ' week' ) );

echo "# Weekly Notes - Week $weekNumber\n\n";
echo "# $monday\n\n";
echo "# $tuesday\n\n";
echo "# $wednesday\n\n";
echo "# $thursday\n\n";
echo "# $friday\n\n";

echo "## TODO\n";
echo "- [ ] \n";
